# Generated by Django 5.0.4 on 2024-05-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_certifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
