# Generated by Django 5.0.4 on 2024-05-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_certifications', '0002_certification_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='image_relative_url',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='remark',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='report_issue_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='report_no',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
