# Generated by Django 5.0.4 on 2024-05-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_certifications', '0005_certification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='alert_threshold',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='certification',
            name='risk_threshold',
            field=models.IntegerField(default=90),
        ),
    ]
