# Generated by Django 5.0.4 on 2024-05-18 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_certifications', '0006_certification_alert_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='alert_threshold',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='risk_threshold',
        ),
    ]
