# Generated by Django 5.0.4 on 2024-05-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_certifications', '0007_remove_certification_alert_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='alert_threshold',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='certification',
            name='risk_threshold',
            field=models.IntegerField(default=90),
        ),
    ]
