# Generated by Django 5.0.4 on 2024-05-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_certifications', '0008_certification_alert_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='status',
            field=models.CharField(choices=[('activate', 'Activate'), ('risk', 'Risk'), ('alert', 'Alert')], default='activate', max_length=15),
        ),
    ]
