# Generated by Django 5.0.4 on 2024-05-21 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_certifications', '0009_alter_certification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='status',
        ),
    ]
