# Generated by Django 5.0.4 on 2024-05-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_certifications', '0011_certification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='report_no',
        ),
        migrations.AlterField(
            model_name='certification',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='certification',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='image_relative_url',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='certification',
            name='indoor_model_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='certification',
            name='outdoor_model_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='certification',
            name='report_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='risk_threshold',
            field=models.IntegerField(default=120),
        ),
    ]
