# Generated by Django 5.0.4 on 2024-05-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_certifications', '0015_alter_certification_expire_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndoorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OutdoorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='indoor_model_name',
            new_name='certificate_name',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='outdoor_model_name',
        ),
        migrations.AddField(
            model_name='certification',
            name='indoor_models',
            field=models.ManyToManyField(related_name='certifications', to='app_certifications.indoormodel'),
        ),
        migrations.AddField(
            model_name='certification',
            name='outdoor_models',
            field=models.ManyToManyField(related_name='certifications', to='app_certifications.outdoormodel'),
        ),
    ]
