# Generated by Django 5.0.4 on 2024-05-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_certifications', '0016_indoormodel_outdoormodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='indoor_models',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='outdoor_models',
        ),
        migrations.AddField(
            model_name='certification',
            name='certificate_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='issue_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='report_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='certificate_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='IndoorModel',
        ),
        migrations.AddField(
            model_name='certification',
            name='indoor_models',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='OutdoorModel',
        ),
        migrations.AddField(
            model_name='certification',
            name='outdoor_models',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
