# Generated by Django 5.0.4 on 2024-05-24 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_certifications', '0017_remove_certification_indoor_models_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('risk_threshold', models.IntegerField(default=120)),
                ('alert_threshold', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='IndoorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OutdoorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='certification',
            name='alert_threshold',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='certificate_no',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='expire_date',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='image_relative_url',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='indoor_models',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='outdoor_models',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='report_issue_date',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='report_no',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='risk_threshold',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='status',
        ),
        migrations.AlterField(
            model_name='certification',
            name='certificate_name',
            field=models.CharField(default='Please enter the country name. ', max_length=255),
        ),
        migrations.AlterField(
            model_name='certification',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='app_certifications.country'),
        ),
        migrations.CreateModel(
            name='IndoorOutdoorPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indoor_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outdoor_pairs', to='app_certifications.indoormodel')),
                ('outdoor_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indoor_pairs', to='app_certifications.outdoormodel')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_no', models.CharField(max_length=255)),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('report_issue_date', models.DateTimeField(blank=True, null=True)),
                ('report_no', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('activate', 'Activate'), ('risk', 'Risk'), ('alert', 'Alert')], default='activate', max_length=10)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_numbers', to='app_certifications.certification')),
                ('indoor_models', models.ManyToManyField(related_name='certificate_numbers', to='app_certifications.indoormodel')),
                ('outdoor_models', models.ManyToManyField(related_name='certificate_numbers', to='app_certifications.outdoormodel')),
            ],
        ),
    ]
