# Generated by Django 5.0.4 on 2024-05-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_certifications', '0018_country_indoormodel_outdoormodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image_relative_url',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
    ]
